name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            pm2 delete cse --silent
            cd site
            git reset --hard HEAD
            git clean -f -d
            git pull
            cd backend
            npm i --force
            pm2 start index.js --name cse
