name: executing remote ssh commands using password
uses: appleboy/ssh-action@master
with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}
    script: |
        cd site
        git pull
        npm run start
